/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.forms;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author lee
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
         getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        login_Panel = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        login_button = new javax.swing.JButton();
        login_PW = new javax.swing.JLabel();
        login_ID = new javax.swing.JLabel();
        login_ID_Text = new javax.swing.JTextField();
        login_PW_Text = new javax.swing.JPasswordField();
        logo1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        register_Panel = new javax.swing.JPanel();
        register_Name = new javax.swing.JLabel();
        register_ID = new javax.swing.JLabel();
        register_PW = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        register_confirm = new javax.swing.JButton();
        register_Name_Text = new javax.swing.JTextField();
        register_ID_Text = new javax.swing.JTextField();
        register_PW_Text = new javax.swing.JPasswordField();
        register_Phone = new javax.swing.JLabel();
        register_Phone_Text = new javax.swing.JTextField();
        shop_Panel1 = new javax.swing.JPanel();
        reservation_Check = new javax.swing.JCheckBox();
        left_seat_Check = new javax.swing.JCheckBox();
        food_type_Combo = new javax.swing.JComboBox<>();
        shop_Name = new javax.swing.JLabel();
        shop_Phone = new javax.swing.JLabel();
        shop_Address = new javax.swing.JLabel();
        shop_Name_Text = new javax.swing.JTextField();
        shop_Phone_Text = new javax.swing.JTextField();
        shop_Address_Text = new javax.swing.JTextField();
        shop1_title = new javax.swing.JLabel();
        shop1_next_button = new javax.swing.JButton();
        shop_Panel2 = new javax.swing.JPanel();
        shop2_title = new javax.swing.JLabel();
        shop2_label1 = new javax.swing.JLabel();
        shop2_label2 = new javax.swing.JLabel();
        shop2_Mon_check = new javax.swing.JCheckBox();
        shop2_Tue_check = new javax.swing.JCheckBox();
        shop2_Wen_check = new javax.swing.JCheckBox();
        shop2_Thr_check = new javax.swing.JCheckBox();
        shop2_Fri_check = new javax.swing.JCheckBox();
        shop2_Sat_check = new javax.swing.JCheckBox();
        shop2_Sun_check = new javax.swing.JCheckBox();
        shop2_label3 = new javax.swing.JLabel();
        shop2_Break_check = new javax.swing.JCheckBox();
        shop2_Break_Startbox = new javax.swing.JComboBox<>();
        shop2_Break_Endbox = new javax.swing.JComboBox<>();
        shop2_label4 = new javax.swing.JLabel();
        shop2_label5 = new javax.swing.JLabel();
        shop2_next_button = new javax.swing.JButton();
        shop_Panel3 = new javax.swing.JPanel();
        shop3_title = new javax.swing.JLabel();
        shop3_label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        shop3_Mon_Start = new javax.swing.JComboBox<>();
        shop3_Mon_End = new javax.swing.JComboBox<>();
        shop3_Tue_Start = new javax.swing.JComboBox<>();
        shop3_Tue_End = new javax.swing.JComboBox<>();
        shop3_Wen_Start = new javax.swing.JComboBox<>();
        shop3_Wen_End = new javax.swing.JComboBox<>();
        shop3_Thr_Start = new javax.swing.JComboBox<>();
        shop3_Thr_End = new javax.swing.JComboBox<>();
        shop3_Fri_Start = new javax.swing.JComboBox<>();
        shop3_Fri_End = new javax.swing.JComboBox<>();
        shop3_Sat_Start = new javax.swing.JComboBox<>();
        shop3_Sat_End = new javax.swing.JComboBox<>();
        shop3_Sun_Start = new javax.swing.JComboBox<>();
        shop3_Sun_End = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        login_Panel.setBackground(new java.awt.Color(255, 255, 255));

        register_button.setBackground(new java.awt.Color(255, 255, 255));
        register_button.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_button.setForeground(new java.awt.Color(153, 153, 0));
        register_button.setText("회원가입");
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        login_button.setBackground(new java.awt.Color(255, 255, 255));
        login_button.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        login_button.setForeground(new java.awt.Color(153, 153, 0));
        login_button.setText("로그인");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        login_PW.setBackground(new java.awt.Color(255, 255, 255));
        login_PW.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        login_PW.setForeground(new java.awt.Color(153, 153, 0));
        login_PW.setText("PW");

        login_ID.setBackground(new java.awt.Color(255, 255, 255));
        login_ID.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        login_ID.setForeground(new java.awt.Color(153, 153, 0));
        login_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_ID.setText("ID");

        login_ID_Text.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        login_ID_Text.setText("jTextField1");

        login_PW_Text.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        login_PW_Text.setText("jPasswordField1");

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/logo2.PNG"))); // NOI18N

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/pos/forms/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout login_PanelLayout = new javax.swing.GroupLayout(login_Panel);
        login_Panel.setLayout(login_PanelLayout);
        login_PanelLayout.setHorizontalGroup(
            login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_PanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                                .addComponent(logo1)
                                .addGap(219, 219, 219))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128))))
                    .addGroup(login_PanelLayout.createSequentialGroup()
                        .addComponent(login_PW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_PW_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(login_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(register_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                        .addComponent(login_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
        );
        login_PanelLayout.setVerticalGroup(
            login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(logo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_ID))
                .addGap(18, 18, 18)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_PW)
                    .addComponent(login_PW_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register_button)
                .addGap(12, 12, 12))
        );

        mainPanel.add(login_Panel, "card1");

        register_Panel.setBackground(new java.awt.Color(255, 255, 255));
        register_Panel.setForeground(new java.awt.Color(153, 153, 0));

        register_Name.setBackground(new java.awt.Color(255, 255, 255));
        register_Name.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_Name.setForeground(new java.awt.Color(153, 153, 0));
        register_Name.setText("이름");

        register_ID.setBackground(new java.awt.Color(255, 255, 255));
        register_ID.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_ID.setForeground(new java.awt.Color(153, 153, 0));
        register_ID.setText("ID");

        register_PW.setBackground(new java.awt.Color(255, 255, 255));
        register_PW.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_PW.setForeground(new java.awt.Color(153, 153, 0));
        register_PW.setText("PW");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("회원가입");

        register_confirm.setBackground(new java.awt.Color(255, 255, 255));
        register_confirm.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        register_confirm.setForeground(new java.awt.Color(153, 153, 0));
        register_confirm.setText("확인");
        register_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_confirmActionPerformed(evt);
            }
        });

        register_Name_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_Name_Text.setText("jTextField2");

        register_ID_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_ID_Text.setText("jTextField3");

        register_PW_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_PW_Text.setText("jPasswordField2");

        register_Phone.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_Phone.setForeground(new java.awt.Color(153, 153, 0));
        register_Phone.setText("휴대폰 번호");

        register_Phone_Text.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        register_Phone_Text.setText("jTextField4");

        javax.swing.GroupLayout register_PanelLayout = new javax.swing.GroupLayout(register_Panel);
        register_Panel.setLayout(register_PanelLayout);
        register_PanelLayout.setHorizontalGroup(
            register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_PanelLayout.createSequentialGroup()
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(register_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(register_PanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(register_ID)
                                    .addComponent(register_PW)
                                    .addComponent(register_Name))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(register_PW_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(register_ID_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(register_Name_Text)))))
                    .addGroup(register_PanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(register_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(register_PanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(register_Phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(register_Phone_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        register_PanelLayout.setVerticalGroup(
            register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_ID_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(register_Name))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_ID)
                    .addComponent(register_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_PW)
                    .addComponent(register_PW_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(register_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(register_Phone)
                    .addComponent(register_Phone_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(register_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        mainPanel.add(register_Panel, "card2");

        shop_Panel1.setBackground(new java.awt.Color(255, 255, 255));

        reservation_Check.setBackground(new java.awt.Color(255, 255, 255));
        reservation_Check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        reservation_Check.setForeground(new java.awt.Color(153, 153, 0));
        reservation_Check.setText("예약");

        left_seat_Check.setBackground(new java.awt.Color(255, 255, 255));
        left_seat_Check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        left_seat_Check.setForeground(new java.awt.Color(153, 153, 0));
        left_seat_Check.setText("잔여좌석");

        food_type_Combo.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        food_type_Combo.setForeground(new java.awt.Color(153, 153, 0));
        food_type_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "한식", "중식", "일식", "양식" }));
        food_type_Combo.setFocusable(false);

        shop_Name.setBackground(new java.awt.Color(255, 255, 255));
        shop_Name.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop_Name.setForeground(new java.awt.Color(153, 153, 0));
        shop_Name.setText("매장 이름");

        shop_Phone.setBackground(new java.awt.Color(255, 255, 255));
        shop_Phone.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop_Phone.setForeground(new java.awt.Color(153, 153, 0));
        shop_Phone.setText("매장 전화번호");

        shop_Address.setBackground(new java.awt.Color(255, 255, 255));
        shop_Address.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop_Address.setForeground(new java.awt.Color(153, 153, 0));
        shop_Address.setText("매장 주소");

        shop_Name_Text.setText("jTextField6");

        shop_Phone_Text.setText("jTextField7");

        shop_Address_Text.setText("jTextField8");

        shop1_title.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        shop1_title.setForeground(new java.awt.Color(153, 153, 0));
        shop1_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop1_title.setText("매장 정보 입력");
        shop1_title.setToolTipText("");

        shop1_next_button.setBackground(new java.awt.Color(255, 255, 255));
        shop1_next_button.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop1_next_button.setForeground(new java.awt.Color(153, 153, 0));
        shop1_next_button.setText("다음");
        shop1_next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop1_next_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shop_Panel1Layout = new javax.swing.GroupLayout(shop_Panel1);
        shop_Panel1.setLayout(shop_Panel1Layout);
        shop_Panel1Layout.setHorizontalGroup(
            shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(shop_Panel1Layout.createSequentialGroup()
                        .addComponent(left_seat_Check)
                        .addGap(41, 41, 41)
                        .addComponent(reservation_Check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(food_type_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shop1_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(shop_Panel1Layout.createSequentialGroup()
                        .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop_Address)
                            .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shop_Phone, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(shop_Name)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shop_Address_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(shop_Phone_Text))))
                    .addComponent(shop1_next_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        shop_Panel1Layout.setVerticalGroup(
            shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shop1_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop_Name)
                    .addComponent(shop_Name_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop_Phone)
                    .addComponent(shop_Phone_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop_Address)
                    .addComponent(shop_Address_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(shop_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(left_seat_Check)
                    .addComponent(reservation_Check)
                    .addComponent(food_type_Combo))
                .addGap(38, 38, 38)
                .addComponent(shop1_next_button)
                .addGap(73, 73, 73))
        );

        mainPanel.add(shop_Panel1, "card3");

        shop_Panel2.setBackground(new java.awt.Color(255, 255, 255));

        shop2_title.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        shop2_title.setForeground(new java.awt.Color(153, 153, 0));
        shop2_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_title.setText("매장 정보 입력");

        shop2_label1.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        shop2_label1.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_label1.setText("영업시간");

        shop2_label2.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_label2.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label2.setText("휴일을 선택하세요");

        shop2_Mon_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Mon_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Mon_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Mon_check.setText("월");
        shop2_Mon_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Mon_checkItemStateChanged(evt);
            }
        });

        shop2_Tue_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Tue_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Tue_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Tue_check.setText("화");
        shop2_Tue_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Tue_checkItemStateChanged(evt);
            }
        });

        shop2_Wen_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Wen_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Wen_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Wen_check.setText("수");
        shop2_Wen_check.setToolTipText("");
        shop2_Wen_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Wen_checkItemStateChanged(evt);
            }
        });

        shop2_Thr_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Thr_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Thr_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Thr_check.setText("목");
        shop2_Thr_check.setToolTipText("");
        shop2_Thr_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Thr_checkItemStateChanged(evt);
            }
        });

        shop2_Fri_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Fri_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Fri_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Fri_check.setText("금");
        shop2_Fri_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Fri_checkItemStateChanged(evt);
            }
        });

        shop2_Sat_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Sat_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Sat_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Sat_check.setText("토");
        shop2_Sat_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Sat_checkItemStateChanged(evt);
            }
        });

        shop2_Sun_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Sun_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Sun_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Sun_check.setText("일");
        shop2_Sun_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Sun_checkItemStateChanged(evt);
            }
        });

        shop2_label3.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_label3.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label3.setText("Break 유무를 선택하세요");

        shop2_Break_check.setBackground(new java.awt.Color(255, 255, 255));
        shop2_Break_check.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Break_check.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Break_check.setText("Break");
        shop2_Break_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                shop2_Break_checkItemStateChanged(evt);
            }
        });

        shop2_Break_Startbox.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Break_Startbox.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Break_Startbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        shop2_Break_Startbox.setToolTipText("");
        shop2_Break_Startbox.setEnabled(false);

        shop2_Break_Endbox.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_Break_Endbox.setForeground(new java.awt.Color(153, 153, 0));
        shop2_Break_Endbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        shop2_Break_Endbox.setEnabled(false);

        shop2_label4.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_label4.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_label4.setText("~");

        shop2_label5.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop2_label5.setForeground(new java.awt.Color(153, 153, 0));
        shop2_label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop2_label5.setText("Break time");

        shop2_next_button.setBackground(new java.awt.Color(255, 255, 255));
        shop2_next_button.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        shop2_next_button.setForeground(new java.awt.Color(153, 153, 0));
        shop2_next_button.setText("다음");
        shop2_next_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop2_next_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shop_Panel2Layout = new javax.swing.GroupLayout(shop_Panel2);
        shop_Panel2.setLayout(shop_Panel2Layout);
        shop_Panel2Layout.setHorizontalGroup(
            shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shop2_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shop2_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shop_Panel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shop_Panel2Layout.createSequentialGroup()
                        .addComponent(shop2_Break_Startbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shop2_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shop2_Break_Endbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shop2_label5)
                    .addComponent(shop2_next_button, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop2_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(shop_Panel2Layout.createSequentialGroup()
                        .addComponent(shop2_Mon_check)
                        .addGap(18, 18, 18)
                        .addComponent(shop2_Tue_check)
                        .addGap(18, 18, 18)
                        .addComponent(shop2_Wen_check)
                        .addGap(18, 18, 18)
                        .addComponent(shop2_Thr_check)
                        .addGap(18, 18, 18)
                        .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(shop_Panel2Layout.createSequentialGroup()
                                .addComponent(shop2_Fri_check)
                                .addGap(18, 18, 18)
                                .addComponent(shop2_Sat_check))
                            .addComponent(shop2_Break_check))
                        .addGap(18, 18, 18)
                        .addComponent(shop2_Sun_check))
                    .addComponent(shop2_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        shop_Panel2Layout.setVerticalGroup(
            shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(shop2_title)
                .addGap(18, 18, 18)
                .addComponent(shop2_label1)
                .addGap(65, 65, 65)
                .addComponent(shop2_label2)
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_Wen_check)
                    .addComponent(shop2_Thr_check)
                    .addComponent(shop2_Fri_check)
                    .addComponent(shop2_Sat_check)
                    .addComponent(shop2_Tue_check)
                    .addComponent(shop2_Sun_check)
                    .addComponent(shop2_Mon_check))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_label3)
                    .addComponent(shop2_Break_check))
                .addGap(18, 18, 18)
                .addComponent(shop2_label5)
                .addGap(18, 18, 18)
                .addGroup(shop_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shop2_Break_Startbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop2_label4)
                    .addComponent(shop2_Break_Endbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(shop2_next_button)
                .addGap(46, 46, 46))
        );

        mainPanel.add(shop_Panel2, "card4");

        shop_Panel3.setBackground(new java.awt.Color(255, 255, 255));

        shop3_title.setFont(new java.awt.Font("굴림", 1, 36)); // NOI18N
        shop3_title.setForeground(new java.awt.Color(153, 153, 0));
        shop3_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop3_title.setText("매장 정보 입력");

        shop3_label1.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        shop3_label1.setForeground(new java.awt.Color(153, 153, 0));
        shop3_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shop3_label1.setText("영업시간");

        jLabel1.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("월");

        jLabel2.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("화");

        jLabel3.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("수");

        jLabel4.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("목");

        jLabel5.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("금");

        jLabel6.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 0));
        jLabel6.setText("토");

        jLabel7.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 0));
        jLabel7.setText("일");

        jLabel8.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("요일           시작        ~       종료");

        shop3_Mon_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Mon_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Mon_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Mon_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Mon_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Mon_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Tue_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Tue_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Tue_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Tue_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Tue_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Tue_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Wen_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Wen_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Wen_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Wen_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Wen_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Wen_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Thr_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Thr_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Thr_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Thr_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Thr_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Thr_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Fri_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Fri_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Fri_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Fri_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Fri_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Fri_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sat_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Sat_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sat_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sat_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Sat_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sat_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sun_Start.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Sun_Start.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sun_Start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        shop3_Sun_End.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
        shop3_Sun_End.setForeground(new java.awt.Color(153, 153, 0));
        shop3_Sun_End.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 0));
        jButton1.setText("등록");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shop_Panel3Layout = new javax.swing.GroupLayout(shop_Panel3);
        shop_Panel3.setLayout(shop_Panel3Layout);
        shop_Panel3Layout.setHorizontalGroup(
            shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shop3_title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(shop3_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shop_Panel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(shop_Panel3Layout.createSequentialGroup()
                        .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(156, 156, 156)
                        .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop3_Mon_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Tue_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Wen_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Thr_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Fri_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Sat_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Sun_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shop3_Mon_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Tue_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Wen_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Thr_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Fri_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Sat_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shop3_Sun_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67))
        );
        shop_Panel3Layout.setVerticalGroup(
            shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shop_Panel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(shop3_title)
                .addGap(18, 18, 18)
                .addComponent(shop3_label1)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(shop3_Mon_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Mon_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(shop3_Tue_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Tue_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(shop3_Wen_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Wen_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(shop3_Thr_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Thr_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(shop3_Fri_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Fri_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(shop3_Sat_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sat_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shop_Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(shop3_Sun_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shop3_Sun_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainPanel.add(shop_Panel3, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_confirmActionPerformed
        // TODO add your handling code here:
          CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card1");
    }//GEN-LAST:event_register_confirmActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card3");
    }//GEN-LAST:event_login_buttonActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card2");
    }//GEN-LAST:event_register_buttonActionPerformed

    private void shop1_next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop1_next_buttonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card4");
    }//GEN-LAST:event_shop1_next_buttonActionPerformed

    private void shop2_Break_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Break_checkItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==1){
             shop2_Break_Startbox.setEnabled(true);
             shop2_Break_Endbox.setEnabled(true);
        }
         else{
             shop2_Break_Startbox.setEnabled(false);
             shop2_Break_Endbox.setEnabled(false);
         }
    }//GEN-LAST:event_shop2_Break_checkItemStateChanged

    private void shop2_next_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop2_next_buttonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "card5");
    }//GEN-LAST:event_shop2_next_buttonActionPerformed

    private void shop2_Mon_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Mon_checkItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==1){
            shop3_Mon_Start.setEnabled(false);
             shop3_Mon_End.setEnabled(false);
             
        }
         else{
             shop3_Mon_Start.setEnabled(true);
             shop3_Mon_End.setEnabled(true);
         }
    }//GEN-LAST:event_shop2_Mon_checkItemStateChanged

    private void shop2_Tue_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Tue_checkItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==1){
             shop3_Tue_Start.setEnabled(false);
             shop3_Tue_End.setEnabled(false);
           
             
        }
         else{
             shop3_Tue_Start.setEnabled(true);
             shop3_Tue_End.setEnabled(true);

         }
    }//GEN-LAST:event_shop2_Tue_checkItemStateChanged

    private void shop2_Wen_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Wen_checkItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==1){
            shop3_Wen_Start.setEnabled(false);
             shop3_Wen_End.setEnabled(false);
             
        }
         else{
             shop3_Wen_Start.setEnabled(true);
             shop3_Wen_End.setEnabled(true);
         }
    }//GEN-LAST:event_shop2_Wen_checkItemStateChanged

    private void shop2_Thr_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Thr_checkItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==1){
            shop3_Thr_Start.setEnabled(false);
             shop3_Thr_End.setEnabled(false);
             
        }
         else{
             shop3_Thr_Start.setEnabled(true);
             shop3_Thr_End.setEnabled(true);
         }
    }//GEN-LAST:event_shop2_Thr_checkItemStateChanged

    private void shop2_Fri_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Fri_checkItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==1){
            shop3_Fri_Start.setEnabled(false);
             shop3_Fri_End.setEnabled(false);
             
        }
         else{
             shop3_Fri_Start.setEnabled(true);
             shop3_Fri_End.setEnabled(true);
         }
    }//GEN-LAST:event_shop2_Fri_checkItemStateChanged

    private void shop2_Sat_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Sat_checkItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==1){
            shop3_Sat_Start.setEnabled(false);
             shop3_Sat_End.setEnabled(false);
             
        }
         else{
             shop3_Sat_Start.setEnabled(true);
             shop3_Sat_End.setEnabled(true);
         }
    }//GEN-LAST:event_shop2_Sat_checkItemStateChanged

    private void shop2_Sun_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_shop2_Sun_checkItemStateChanged
        // TODO add your handling code here:
          if(evt.getStateChange()==1){
            shop3_Sun_Start.setEnabled(false);
             shop3_Sun_End.setEnabled(false);
             
        }
         else{
             shop3_Sun_Start.setEnabled(true);
             shop3_Sun_End.setEnabled(true);
         }
    }//GEN-LAST:event_shop2_Sun_checkItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> food_type_Combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox left_seat_Check;
    private javax.swing.JLabel login_ID;
    private javax.swing.JTextField login_ID_Text;
    private javax.swing.JLabel login_PW;
    private javax.swing.JPasswordField login_PW_Text;
    private javax.swing.JPanel login_Panel;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel register_ID;
    private javax.swing.JTextField register_ID_Text;
    private javax.swing.JLabel register_Name;
    private javax.swing.JTextField register_Name_Text;
    private javax.swing.JLabel register_PW;
    private javax.swing.JPasswordField register_PW_Text;
    private javax.swing.JPanel register_Panel;
    private javax.swing.JLabel register_Phone;
    private javax.swing.JTextField register_Phone_Text;
    private javax.swing.JButton register_button;
    private javax.swing.JButton register_confirm;
    private javax.swing.JCheckBox reservation_Check;
    private javax.swing.JButton shop1_next_button;
    private javax.swing.JLabel shop1_title;
    private javax.swing.JComboBox<String> shop2_Break_Endbox;
    private javax.swing.JComboBox<String> shop2_Break_Startbox;
    private javax.swing.JCheckBox shop2_Break_check;
    private javax.swing.JCheckBox shop2_Fri_check;
    private javax.swing.JCheckBox shop2_Mon_check;
    private javax.swing.JCheckBox shop2_Sat_check;
    private javax.swing.JCheckBox shop2_Sun_check;
    private javax.swing.JCheckBox shop2_Thr_check;
    private javax.swing.JCheckBox shop2_Tue_check;
    private javax.swing.JCheckBox shop2_Wen_check;
    private javax.swing.JLabel shop2_label1;
    private javax.swing.JLabel shop2_label2;
    private javax.swing.JLabel shop2_label3;
    private javax.swing.JLabel shop2_label4;
    private javax.swing.JLabel shop2_label5;
    private javax.swing.JButton shop2_next_button;
    private javax.swing.JLabel shop2_title;
    private javax.swing.JComboBox<String> shop3_Fri_End;
    private javax.swing.JComboBox<String> shop3_Fri_Start;
    private javax.swing.JComboBox<String> shop3_Mon_End;
    private javax.swing.JComboBox<String> shop3_Mon_Start;
    private javax.swing.JComboBox<String> shop3_Sat_End;
    private javax.swing.JComboBox<String> shop3_Sat_Start;
    private javax.swing.JComboBox<String> shop3_Sun_End;
    private javax.swing.JComboBox<String> shop3_Sun_Start;
    private javax.swing.JComboBox<String> shop3_Thr_End;
    private javax.swing.JComboBox<String> shop3_Thr_Start;
    private javax.swing.JComboBox<String> shop3_Tue_End;
    private javax.swing.JComboBox<String> shop3_Tue_Start;
    private javax.swing.JComboBox<String> shop3_Wen_End;
    private javax.swing.JComboBox<String> shop3_Wen_Start;
    private javax.swing.JLabel shop3_label1;
    private javax.swing.JLabel shop3_title;
    private javax.swing.JLabel shop_Address;
    private javax.swing.JTextField shop_Address_Text;
    private javax.swing.JLabel shop_Name;
    private javax.swing.JTextField shop_Name_Text;
    private javax.swing.JPanel shop_Panel1;
    private javax.swing.JPanel shop_Panel2;
    private javax.swing.JPanel shop_Panel3;
    private javax.swing.JLabel shop_Phone;
    private javax.swing.JTextField shop_Phone_Text;
    // End of variables declaration//GEN-END:variables
}
